Repository wecode-bootcamp-korea/fullstack1-2nd-SKYROCKET-frontend, pull requests merged in 2021-08, with the labels that each got.

#3 [감하영] Login, SignUp 컴포넌트 레이아웃 구현 및 회원가입 약관동의 checkbox 전체선택 기능 구현
  src/Routes.js
  src/assets/LogoKakao.svg
  src/assets/LogoSkyrocket.svg
  src/assets/LogoSkyrocketWithIcon.svg
  src/pages/Login/Login.js
  src/pages/Member/Login/Login.js
  src/pages/Member/SignUp/SignUp.js
  src/pages/Member/SignUp/components/EmailSignUp.js
  src/pages/Member/SignUp/components/KakaoSignUp.js
  src/pages/Member/components/Button.js
  src/pages/Member/components/Copyright.js
  src/pages/Member/components/FormBox.js
  src/pages/Member/components/Header.js
  src/pages/Member/components/Input.js
  src/pages/Member/components/OrDivider.js
  src/pages/Member/components/SignUpOrSignIn.js
  src/pages/Member/data/checkBoxes.js
  src/pages/Member/index.js
  src/pages/SignUp/SignUp.js
  src/styles/GlobalStyles.js
Labels: Status: Accepted, Status: 수정 요청

#4 [신수호] 메인페이지 리뷰반영중
  package-lock.json
  public/data/ProductCardData.json
  public/data/SlideImgData.json
  src/pages/Main/Main.js
  src/pages/Main/components/ProjectCard.js
  src/pages/Main/components/ProjectList.js
  src/pages/Main/components/Slider.js
  src/pages/Main/components/SliderImgComp.js
  src/pages/Main/components/TextBoxComp.js
Labels: Status: Accepted

#9 [신수호] 푸터 레이아웃 완료
  public/data/FooterData.json
  src/components/Footer/Footer.js
  src/components/Footer/components/FooterCompany.js
  src/components/Footer/components/FooterContent.js
  src/components/Footer/components/FooterContentWrap.js
Labels: Status: Accepted

#8 [신수호] 후원내역 페이지 레이아웃 완성
  public/data/PledgesCardData.json
  src/pages/Pledges/Pledges.js
  src/pages/Pledges/components/PledgesCard.js
  src/pages/Pledges/components/PledgesList.js
  src/pages/Pledges/components/PledgesTitle.js
Labels: Status: 리뷰 진행중

#12 [감하영] 리스트 페이지 레이아웃 구현 및 리스트 API 연계 및 메인, 푸터, 후원현황, 헤더 레이아웃 일부 수정
  src/components/Footer/components/FooterCompany.js
  src/components/Header/components/LogoutLink.js
  src/hooks/useProjectsData.js
  src/pages/List/List.js
  src/pages/List/components/ProgressBar.js
  src/pages/List/components/ProjectCounter.js
  src/pages/List/components/ProjectItemCard.js
  src/pages/List/components/ProjectList.js
  src/pages/List/components/ProjectListGrid.js
  src/pages/Main/components/ProjectCard.js
  src/pages/Main/components/ProjectList.js
  src/pages/Pledges/Pledges.js
  src/pages/Pledges/components/PledgesCard.js
  src/styles/theme.js
  src/utils.js
Labels: Status: 추가 기능 구현중
